production:
  adapter: redis
  url: redis://redistogo:8c056998a63444058504ecd87234df72@chubb.redistogo.com:9399/
  # channel_prefix: boomback_production

development:
  adapter: async

test:
  adapter: async
